# Generated by Django 4.0.2 on 2022-02-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_tblclassmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblClassModel',
        ),
    ]
